/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reasyncserver.vistas;

import java.awt.CardLayout;
import reasyncserver.vistas.controles.ReaSyncController;

/**
 *
 * @author jdiaz
 */
public class ReaSyncServer extends javax.swing.JFrame {

    /**
     * Creates new form ReaSyncServer
     */
    public ReaSyncServer() {
        initComponents();
        myinitComponents();
    }

    public void myinitComponents() {
        ReaSyncController control = new ReaSyncController(this);
        initActionListeners(control);
        initMouseListeners(control);
    }

    private void initActionListeners(ReaSyncController control) {
        reasyncServerStartButton.addActionListener(control.getActionController());
        reasyncServerStopButton.addActionListener(control.getActionController());
        conexionBDButton.addActionListener(control.getActionController());
    }

    private void initMouseListeners(ReaSyncController control) {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuContainerPanel = new javax.swing.JPanel();
        servicesMenuButton = new javax.swing.JButton();
        homeLogoMenuButton = new javax.swing.JButton();
        logMenuButton = new javax.swing.JButton();
        clientsMenuButton = new javax.swing.JButton();
        bodyContainerPanel = new javax.swing.JPanel();
        homePrincipalPanel = new javax.swing.JPanel();
        homeTitlePanel = new javax.swing.JPanel();
        homeTitleLabel = new javax.swing.JLabel();
        homeTitleSeparator = new javax.swing.JSeparator();
        homeContainerPanel = new javax.swing.JPanel();
        homeContainerBanner = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        homeContainerServicesPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        reasyncServerLabel = new javax.swing.JLabel();
        reaSyncServerPortLabel = new javax.swing.JLabel();
        logPrincipalPanel = new javax.swing.JPanel();
        logTitlePanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        logContainerPanel = new javax.swing.JPanel();
        logScroll = new javax.swing.JScrollPane();
        logTextArea = new javax.swing.JTextArea();
        clientsPrincipalPanel = new javax.swing.JPanel();
        clientsTitlePanel = new javax.swing.JPanel();
        titleClientsLabel = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        clientsContainerPanel = new javax.swing.JPanel();
        clientsTableScroll = new javax.swing.JScrollPane();
        clientsTable = new javax.swing.JTable();
        servicesPrincipalPanel = new javax.swing.JPanel();
        tilteServicesPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        servicesContainerPanel = new javax.swing.JPanel();
        servicesBDPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        conexionBDButton = new javax.swing.JButton();
        mysqlServicesServiceLabel = new javax.swing.JLabel();
        servicesFTPPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        ftpServicesServiceLabel = new javax.swing.JLabel();
        ftpServiceButton = new javax.swing.JButton();
        servicesReaSyncPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        reasyncServerStartButton = new javax.swing.JButton();
        reasyncServerStopButton = new javax.swing.JButton();
        reasyncServicesServerLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ipReaSyncServerLabel = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        portReaSyncServerField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 450));
        setResizable(false);

        menuContainerPanel.setBackground(new java.awt.Color(255, 153, 0));
        menuContainerPanel.setLayout(new java.awt.GridLayout(1, 5));

        servicesMenuButton.setBackground(new java.awt.Color(255, 153, 0));
        servicesMenuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reasyncserver/vistas/imagenes/database.png"))); // NOI18N
        servicesMenuButton.setBorderPainted(false);
        servicesMenuButton.setContentAreaFilled(false);
        servicesMenuButton.setDefaultCapable(false);
        servicesMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicesMenuButtonActionPerformed(evt);
            }
        });
        menuContainerPanel.add(servicesMenuButton);

        homeLogoMenuButton.setBackground(new java.awt.Color(255, 153, 0));
        homeLogoMenuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reasyncserver/vistas/imagenes/statuslogo.png"))); // NOI18N
        homeLogoMenuButton.setBorderPainted(false);
        homeLogoMenuButton.setContentAreaFilled(false);
        homeLogoMenuButton.setDefaultCapable(false);
        homeLogoMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeLogoMenuButtonActionPerformed(evt);
            }
        });
        menuContainerPanel.add(homeLogoMenuButton);

        logMenuButton.setBackground(new java.awt.Color(255, 153, 0));
        logMenuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reasyncserver/vistas/imagenes/file.png"))); // NOI18N
        logMenuButton.setBorderPainted(false);
        logMenuButton.setContentAreaFilled(false);
        logMenuButton.setDefaultCapable(false);
        logMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logMenuButtonActionPerformed(evt);
            }
        });
        menuContainerPanel.add(logMenuButton);

        clientsMenuButton.setBackground(new java.awt.Color(255, 153, 0));
        clientsMenuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reasyncserver/vistas/imagenes/users-group.png"))); // NOI18N
        clientsMenuButton.setBorderPainted(false);
        clientsMenuButton.setContentAreaFilled(false);
        clientsMenuButton.setDefaultCapable(false);
        clientsMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientsMenuButtonActionPerformed(evt);
            }
        });
        menuContainerPanel.add(clientsMenuButton);

        getContentPane().add(menuContainerPanel, java.awt.BorderLayout.PAGE_END);

        bodyContainerPanel.setBackground(new java.awt.Color(255, 255, 255));
        bodyContainerPanel.setLayout(new java.awt.CardLayout());

        homePrincipalPanel.setBackground(new java.awt.Color(255, 255, 255));
        homePrincipalPanel.setLayout(new java.awt.BorderLayout());

        homeTitlePanel.setBackground(new java.awt.Color(255, 255, 255));

        homeTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        homeTitleLabel.setText("ReaSync Server");

        javax.swing.GroupLayout homeTitlePanelLayout = new javax.swing.GroupLayout(homeTitlePanel);
        homeTitlePanel.setLayout(homeTitlePanelLayout);
        homeTitlePanelLayout.setHorizontalGroup(
            homeTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeTitlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homeTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homeTitlePanelLayout.createSequentialGroup()
                        .addComponent(homeTitleLabel)
                        .addGap(0, 380, Short.MAX_VALUE))
                    .addComponent(homeTitleSeparator))
                .addContainerGap())
        );
        homeTitlePanelLayout.setVerticalGroup(
            homeTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeTitlePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homeTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeTitleSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        homePrincipalPanel.add(homeTitlePanel, java.awt.BorderLayout.PAGE_START);

        homeContainerPanel.setBackground(new java.awt.Color(255, 255, 255));
        homeContainerPanel.setLayout(new java.awt.BorderLayout());

        homeContainerBanner.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Todos los servicios estan conectados.");

        javax.swing.GroupLayout homeContainerBannerLayout = new javax.swing.GroupLayout(homeContainerBanner);
        homeContainerBanner.setLayout(homeContainerBannerLayout);
        homeContainerBannerLayout.setHorizontalGroup(
            homeContainerBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeContainerBannerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(493, Short.MAX_VALUE))
        );
        homeContainerBannerLayout.setVerticalGroup(
            homeContainerBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeContainerBannerLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(41, 41, 41))
        );

        homeContainerPanel.add(homeContainerBanner, java.awt.BorderLayout.PAGE_END);

        homeContainerServicesPanel.setLayout(new java.awt.GridLayout(1, 3));

        jPanel3.setBackground(new java.awt.Color(245, 245, 245));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("FTP");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel2)
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        homeContainerServicesPanel.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(250, 250, 250));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Base de Datos");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        homeContainerServicesPanel.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(245, 245, 245));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Servidor");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel4)
                        .addGap(0, 67, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reasyncServerLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator3)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(reaSyncServerPortLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reasyncServerLabel)
                .addGap(18, 18, 18)
                .addComponent(reaSyncServerPortLabel)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        homeContainerServicesPanel.add(jPanel5);

        homeContainerPanel.add(homeContainerServicesPanel, java.awt.BorderLayout.CENTER);

        homePrincipalPanel.add(homeContainerPanel, java.awt.BorderLayout.CENTER);

        bodyContainerPanel.add(homePrincipalPanel, "homePrincipalPanel");

        logPrincipalPanel.setBackground(new java.awt.Color(255, 255, 255));
        logPrincipalPanel.setLayout(new java.awt.BorderLayout());

        logTitlePanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("¿Qué ha ocurrido?");

        javax.swing.GroupLayout logTitlePanelLayout = new javax.swing.GroupLayout(logTitlePanel);
        logTitlePanel.setLayout(logTitlePanelLayout);
        logTitlePanelLayout.setHorizontalGroup(
            logTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logTitlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(logTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(logTitlePanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 498, Short.MAX_VALUE))
                    .addComponent(jSeparator4))
                .addContainerGap())
        );
        logTitlePanelLayout.setVerticalGroup(
            logTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logTitlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        logPrincipalPanel.add(logTitlePanel, java.awt.BorderLayout.PAGE_START);

        logContainerPanel.setBackground(new java.awt.Color(255, 255, 255));
        logContainerPanel.setLayout(new java.awt.GridLayout(1, 0));

        logScroll.setBackground(new java.awt.Color(255, 255, 255));

        logTextArea.setColumns(20);
        logTextArea.setRows(5);
        logScroll.setViewportView(logTextArea);

        logContainerPanel.add(logScroll);

        logPrincipalPanel.add(logContainerPanel, java.awt.BorderLayout.CENTER);

        bodyContainerPanel.add(logPrincipalPanel, "logPrincipalPanel");

        clientsPrincipalPanel.setBackground(new java.awt.Color(255, 255, 255));
        clientsPrincipalPanel.setLayout(new java.awt.BorderLayout());

        clientsTitlePanel.setBackground(new java.awt.Color(255, 255, 255));

        titleClientsLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titleClientsLabel.setText("Clientes Conectados");

        javax.swing.GroupLayout clientsTitlePanelLayout = new javax.swing.GroupLayout(clientsTitlePanel);
        clientsTitlePanel.setLayout(clientsTitlePanelLayout);
        clientsTitlePanelLayout.setHorizontalGroup(
            clientsTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientsTitlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientsTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clientsTitlePanelLayout.createSequentialGroup()
                        .addComponent(titleClientsLabel)
                        .addGap(0, 482, Short.MAX_VALUE))
                    .addComponent(jSeparator5))
                .addContainerGap())
        );
        clientsTitlePanelLayout.setVerticalGroup(
            clientsTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientsTitlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleClientsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        clientsPrincipalPanel.add(clientsTitlePanel, java.awt.BorderLayout.PAGE_START);

        clientsContainerPanel.setBackground(new java.awt.Color(255, 255, 255));
        clientsContainerPanel.setLayout(new java.awt.GridLayout(1, 0));

        clientsTableScroll.setViewportView(clientsTable);

        clientsContainerPanel.add(clientsTableScroll);

        clientsPrincipalPanel.add(clientsContainerPanel, java.awt.BorderLayout.CENTER);

        bodyContainerPanel.add(clientsPrincipalPanel, "clientsPrincipalPanel");

        servicesPrincipalPanel.setBackground(new java.awt.Color(255, 255, 255));
        servicesPrincipalPanel.setLayout(new java.awt.BorderLayout());

        tilteServicesPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Servicios");

        javax.swing.GroupLayout tilteServicesPanelLayout = new javax.swing.GroupLayout(tilteServicesPanel);
        tilteServicesPanel.setLayout(tilteServicesPanelLayout);
        tilteServicesPanelLayout.setHorizontalGroup(
            tilteServicesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tilteServicesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tilteServicesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tilteServicesPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 584, Short.MAX_VALUE))
                    .addComponent(jSeparator6))
                .addContainerGap())
        );
        tilteServicesPanelLayout.setVerticalGroup(
            tilteServicesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tilteServicesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        servicesPrincipalPanel.add(tilteServicesPanel, java.awt.BorderLayout.PAGE_START);

        servicesContainerPanel.setBackground(new java.awt.Color(255, 255, 255));
        servicesContainerPanel.setLayout(new java.awt.GridLayout(1, 3));

        servicesBDPanel.setBackground(new java.awt.Color(245, 245, 245));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Base de datos");

        conexionBDButton.setText("Probar Conexión");
        conexionBDButton.setActionCommand("conexionBDButton");

        mysqlServicesServiceLabel.setText("El servicio MYSQL esta detenido");
        mysqlServicesServiceLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout servicesBDPanelLayout = new javax.swing.GroupLayout(servicesBDPanel);
        servicesBDPanel.setLayout(servicesBDPanelLayout);
        servicesBDPanelLayout.setHorizontalGroup(
            servicesBDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(servicesBDPanelLayout.createSequentialGroup()
                .addGroup(servicesBDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(servicesBDPanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, servicesBDPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator7))
                    .addGroup(servicesBDPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mysqlServicesServiceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
                    .addGroup(servicesBDPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(conexionBDButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        servicesBDPanelLayout.setVerticalGroup(
            servicesBDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(servicesBDPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(conexionBDButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                .addComponent(mysqlServicesServiceLabel)
                .addContainerGap())
        );

        servicesContainerPanel.add(servicesBDPanel);

        servicesFTPPanel.setBackground(new java.awt.Color(250, 250, 250));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("FTP Server");

        ftpServicesServiceLabel.setText("El servicio FTP esta detenido");
        ftpServicesServiceLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ftpServiceButton.setText("Verificar Servicio FTP");

        javax.swing.GroupLayout servicesFTPPanelLayout = new javax.swing.GroupLayout(servicesFTPPanel);
        servicesFTPPanel.setLayout(servicesFTPPanelLayout);
        servicesFTPPanelLayout.setHorizontalGroup(
            servicesFTPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(servicesFTPPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(servicesFTPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, servicesFTPPanelLayout.createSequentialGroup()
                        .addGap(0, 68, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, servicesFTPPanelLayout.createSequentialGroup()
                        .addGroup(servicesFTPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ftpServiceButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftpServicesServiceLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        servicesFTPPanelLayout.setVerticalGroup(
            servicesFTPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(servicesFTPPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftpServiceButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                .addComponent(ftpServicesServiceLabel)
                .addContainerGap())
        );

        servicesContainerPanel.add(servicesFTPPanel);

        servicesReaSyncPanel.setBackground(new java.awt.Color(245, 245, 245));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("ReaSync Server");

        reasyncServerStartButton.setText("Iniciar Servidor");
        reasyncServerStartButton.setActionCommand("reasyncServerStartButton");

        reasyncServerStopButton.setText("Detener Servidor");
        reasyncServerStopButton.setActionCommand("reasyncServerStopButton");

        reasyncServicesServerLabel.setText("El servicio ReaSync esta detenido");
        reasyncServicesServerLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("La dirección IP es:");

        ipReaSyncServerLabel.setText("127.0.0.1");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Puerto:");

        portReaSyncServerField.setText("9000");
        portReaSyncServerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portReaSyncServerFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout servicesReaSyncPanelLayout = new javax.swing.GroupLayout(servicesReaSyncPanel);
        servicesReaSyncPanel.setLayout(servicesReaSyncPanelLayout);
        servicesReaSyncPanelLayout.setHorizontalGroup(
            servicesReaSyncPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, servicesReaSyncPanelLayout.createSequentialGroup()
                .addGroup(servicesReaSyncPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, servicesReaSyncPanelLayout.createSequentialGroup()
                        .addGroup(servicesReaSyncPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(servicesReaSyncPanelLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel9))
                            .addGroup(servicesReaSyncPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel13)))
                        .addGap(0, 50, Short.MAX_VALUE))
                    .addGroup(servicesReaSyncPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(servicesReaSyncPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(portReaSyncServerField)
                            .addComponent(ipReaSyncServerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reasyncServerStopButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator9)
                            .addComponent(reasyncServerStartButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reasyncServicesServerLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, servicesReaSyncPanelLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        servicesReaSyncPanelLayout.setVerticalGroup(
            servicesReaSyncPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(servicesReaSyncPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ipReaSyncServerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(portReaSyncServerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(reasyncServerStartButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reasyncServerStopButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(reasyncServicesServerLabel)
                .addContainerGap())
        );

        servicesContainerPanel.add(servicesReaSyncPanel);

        servicesPrincipalPanel.add(servicesContainerPanel, java.awt.BorderLayout.CENTER);

        bodyContainerPanel.add(servicesPrincipalPanel, "servicesPrincipalPanel");

        getContentPane().add(bodyContainerPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void servicesMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicesMenuButtonActionPerformed
        CardLayout panel = (CardLayout) bodyContainerPanel.getLayout();
        panel.show(bodyContainerPanel, "servicesPrincipalPanel");
    }//GEN-LAST:event_servicesMenuButtonActionPerformed

    private void homeLogoMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeLogoMenuButtonActionPerformed
        CardLayout panel = (CardLayout) bodyContainerPanel.getLayout();
        panel.show(bodyContainerPanel, "homePrincipalPanel");
    }//GEN-LAST:event_homeLogoMenuButtonActionPerformed

    private void logMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logMenuButtonActionPerformed
        CardLayout panel = (CardLayout) bodyContainerPanel.getLayout();
        panel.show(bodyContainerPanel, "logPrincipalPanel");
    }//GEN-LAST:event_logMenuButtonActionPerformed

    private void clientsMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientsMenuButtonActionPerformed
        CardLayout panel = (CardLayout) bodyContainerPanel.getLayout();
        panel.show(bodyContainerPanel, "clientsPrincipalPanel");
    }//GEN-LAST:event_clientsMenuButtonActionPerformed

    private void portReaSyncServerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portReaSyncServerFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_portReaSyncServerFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReaSyncServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReaSyncServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReaSyncServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReaSyncServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReaSyncServer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel bodyContainerPanel;
    public javax.swing.JPanel clientsContainerPanel;
    public javax.swing.JButton clientsMenuButton;
    public javax.swing.JPanel clientsPrincipalPanel;
    public javax.swing.JTable clientsTable;
    public javax.swing.JScrollPane clientsTableScroll;
    public javax.swing.JPanel clientsTitlePanel;
    public javax.swing.JButton conexionBDButton;
    public javax.swing.JButton ftpServiceButton;
    public javax.swing.JLabel ftpServicesServiceLabel;
    public javax.swing.JPanel homeContainerBanner;
    public javax.swing.JPanel homeContainerPanel;
    public javax.swing.JPanel homeContainerServicesPanel;
    public javax.swing.JButton homeLogoMenuButton;
    public javax.swing.JPanel homePrincipalPanel;
    public javax.swing.JLabel homeTitleLabel;
    public javax.swing.JPanel homeTitlePanel;
    public javax.swing.JSeparator homeTitleSeparator;
    public javax.swing.JLabel ipReaSyncServerLabel;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JSeparator jSeparator2;
    public javax.swing.JSeparator jSeparator3;
    public javax.swing.JSeparator jSeparator4;
    public javax.swing.JSeparator jSeparator5;
    public javax.swing.JSeparator jSeparator6;
    public javax.swing.JSeparator jSeparator7;
    public javax.swing.JSeparator jSeparator8;
    public javax.swing.JSeparator jSeparator9;
    public javax.swing.JPanel logContainerPanel;
    public javax.swing.JButton logMenuButton;
    public javax.swing.JPanel logPrincipalPanel;
    public javax.swing.JScrollPane logScroll;
    public javax.swing.JTextArea logTextArea;
    public javax.swing.JPanel logTitlePanel;
    public javax.swing.JPanel menuContainerPanel;
    public javax.swing.JLabel mysqlServicesServiceLabel;
    public javax.swing.JTextField portReaSyncServerField;
    public javax.swing.JLabel reaSyncServerPortLabel;
    public javax.swing.JLabel reasyncServerLabel;
    public javax.swing.JButton reasyncServerStartButton;
    public javax.swing.JButton reasyncServerStopButton;
    public javax.swing.JLabel reasyncServicesServerLabel;
    public javax.swing.JPanel servicesBDPanel;
    public javax.swing.JPanel servicesContainerPanel;
    public javax.swing.JPanel servicesFTPPanel;
    public javax.swing.JButton servicesMenuButton;
    public javax.swing.JPanel servicesPrincipalPanel;
    public javax.swing.JPanel servicesReaSyncPanel;
    public javax.swing.JPanel tilteServicesPanel;
    public javax.swing.JLabel titleClientsLabel;
    // End of variables declaration//GEN-END:variables
}
