/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reasyncserver.vistas;

/**
 *
 * @author jdiaz
 */
public class ReaSyncServer extends javax.swing.JFrame {

    /**
     * Creates new form ReaSyncServer
     */
    public ReaSyncServer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuContainerPanel = new javax.swing.JPanel();
        servicesMenuButton = new javax.swing.JButton();
        dirMenuButton = new javax.swing.JButton();
        homeLogoMenuButton = new javax.swing.JButton();
        logMenuButton = new javax.swing.JButton();
        clientsMenuButton = new javax.swing.JButton();
        bodyContainerPanel = new javax.swing.JPanel();
        homePrincipalPanel = new javax.swing.JPanel();
        logPrincipalPanel = new javax.swing.JPanel();
        clientsPrincipalPanel = new javax.swing.JPanel();
        directoriesPrincipalPanel = new javax.swing.JPanel();
        servicesPrincipalPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(650, 450));
        setMinimumSize(new java.awt.Dimension(650, 450));
        setResizable(false);

        menuContainerPanel.setBackground(new java.awt.Color(255, 153, 0));
        menuContainerPanel.setLayout(new java.awt.GridLayout(1, 5));

        servicesMenuButton.setBackground(new java.awt.Color(255, 153, 0));
        servicesMenuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reasyncserver/vistas/imagenes/database.png"))); // NOI18N
        servicesMenuButton.setBorderPainted(false);
        servicesMenuButton.setContentAreaFilled(false);
        servicesMenuButton.setDefaultCapable(false);
        menuContainerPanel.add(servicesMenuButton);

        dirMenuButton.setBackground(new java.awt.Color(255, 153, 0));
        dirMenuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reasyncserver/vistas/imagenes/dir.png"))); // NOI18N
        dirMenuButton.setBorderPainted(false);
        dirMenuButton.setContentAreaFilled(false);
        dirMenuButton.setDefaultCapable(false);
        dirMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dirMenuButtonActionPerformed(evt);
            }
        });
        menuContainerPanel.add(dirMenuButton);

        homeLogoMenuButton.setBackground(new java.awt.Color(255, 153, 0));
        homeLogoMenuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reasyncserver/vistas/imagenes/statuslogo.png"))); // NOI18N
        homeLogoMenuButton.setBorderPainted(false);
        homeLogoMenuButton.setContentAreaFilled(false);
        homeLogoMenuButton.setDefaultCapable(false);
        menuContainerPanel.add(homeLogoMenuButton);

        logMenuButton.setBackground(new java.awt.Color(255, 153, 0));
        logMenuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reasyncserver/vistas/imagenes/file.png"))); // NOI18N
        logMenuButton.setBorderPainted(false);
        logMenuButton.setContentAreaFilled(false);
        logMenuButton.setDefaultCapable(false);
        menuContainerPanel.add(logMenuButton);

        clientsMenuButton.setBackground(new java.awt.Color(255, 153, 0));
        clientsMenuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reasyncserver/vistas/imagenes/users-group.png"))); // NOI18N
        clientsMenuButton.setBorderPainted(false);
        clientsMenuButton.setContentAreaFilled(false);
        clientsMenuButton.setDefaultCapable(false);
        menuContainerPanel.add(clientsMenuButton);

        getContentPane().add(menuContainerPanel, java.awt.BorderLayout.PAGE_END);

        bodyContainerPanel.setBackground(new java.awt.Color(255, 255, 255));
        bodyContainerPanel.setLayout(new java.awt.CardLayout());

        homePrincipalPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout homePrincipalPanelLayout = new javax.swing.GroupLayout(homePrincipalPanel);
        homePrincipalPanel.setLayout(homePrincipalPanelLayout);
        homePrincipalPanelLayout.setHorizontalGroup(
            homePrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 705, Short.MAX_VALUE)
        );
        homePrincipalPanelLayout.setVerticalGroup(
            homePrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );

        bodyContainerPanel.add(homePrincipalPanel, "homePrincipalPanel");

        logPrincipalPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout logPrincipalPanelLayout = new javax.swing.GroupLayout(logPrincipalPanel);
        logPrincipalPanel.setLayout(logPrincipalPanelLayout);
        logPrincipalPanelLayout.setHorizontalGroup(
            logPrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 705, Short.MAX_VALUE)
        );
        logPrincipalPanelLayout.setVerticalGroup(
            logPrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );

        bodyContainerPanel.add(logPrincipalPanel, "logPrincipalPanel");

        clientsPrincipalPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout clientsPrincipalPanelLayout = new javax.swing.GroupLayout(clientsPrincipalPanel);
        clientsPrincipalPanel.setLayout(clientsPrincipalPanelLayout);
        clientsPrincipalPanelLayout.setHorizontalGroup(
            clientsPrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 705, Short.MAX_VALUE)
        );
        clientsPrincipalPanelLayout.setVerticalGroup(
            clientsPrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );

        bodyContainerPanel.add(clientsPrincipalPanel, "clientsPrincipalPanel");

        directoriesPrincipalPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout directoriesPrincipalPanelLayout = new javax.swing.GroupLayout(directoriesPrincipalPanel);
        directoriesPrincipalPanel.setLayout(directoriesPrincipalPanelLayout);
        directoriesPrincipalPanelLayout.setHorizontalGroup(
            directoriesPrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 705, Short.MAX_VALUE)
        );
        directoriesPrincipalPanelLayout.setVerticalGroup(
            directoriesPrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );

        bodyContainerPanel.add(directoriesPrincipalPanel, "directoriesPrincipalPanel");

        servicesPrincipalPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout servicesPrincipalPanelLayout = new javax.swing.GroupLayout(servicesPrincipalPanel);
        servicesPrincipalPanel.setLayout(servicesPrincipalPanelLayout);
        servicesPrincipalPanelLayout.setHorizontalGroup(
            servicesPrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 705, Short.MAX_VALUE)
        );
        servicesPrincipalPanelLayout.setVerticalGroup(
            servicesPrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );

        bodyContainerPanel.add(servicesPrincipalPanel, "servicesPrincipalPanel");

        getContentPane().add(bodyContainerPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dirMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dirMenuButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dirMenuButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReaSyncServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReaSyncServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReaSyncServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReaSyncServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReaSyncServer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyContainerPanel;
    private javax.swing.JButton clientsMenuButton;
    private javax.swing.JPanel clientsPrincipalPanel;
    private javax.swing.JButton dirMenuButton;
    private javax.swing.JPanel directoriesPrincipalPanel;
    private javax.swing.JButton homeLogoMenuButton;
    private javax.swing.JPanel homePrincipalPanel;
    private javax.swing.JButton logMenuButton;
    private javax.swing.JPanel logPrincipalPanel;
    private javax.swing.JPanel menuContainerPanel;
    private javax.swing.JButton servicesMenuButton;
    private javax.swing.JPanel servicesPrincipalPanel;
    // End of variables declaration//GEN-END:variables
}
